services:
  tag.form.type.tag:
    class: ProfilingBundle\Form\TagType
    arguments: ['@doctrine.orm.entity_manager']
    tags:
      - { name: form.type }
#    profiling.example:
#        class: ProfilingBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
